### PR TITLE
Add go to list of backend languages

### PR DESCRIPTION
**Pull request by anubhavcodes**
Update the backend languages to include our beloved Go programming language. 

PTAL

### CODE REVIEW

**Review by TobiasBales — CHANGES_REQUESTED** [review]
can we please create another radar for infrastructure teams?
the needs etc are different and this avoids having conversations why the next product will not be written in go. same for data/rust ❤️ 
all you need to do is create a new csv in the data folder and create a new link with the filename

**Comment by anubhavcodes** [comment]
@TobiasBales thank you for your review, and what you said completely make sense. However this might involve a bit of conversation with the infrastructure team about what tools / languages / framework we agree on together. I will start the conversation and then update the PR with another radar.

**Comment by TobiasBales** [comment]
> @TobiasBales thank you for your review, and what you said completely make sense. However this might involve a bit of conversation with the infrastructure team about what tools / languages / framework we agree on together. I will start the conversation and then update the PR with another radar.

how about adding one that uses just go and whatever linter you use, kubernetes and that is it?
then you have something you can incrementally add to which is always easier than big bang stuff

**Comment by bijancn** [comment]
👍 for separating. I'm also wondering if mixing different backend languages and frameworks is not creating a radar that is too hard too read

**Pull request closed without merging**
